# conda env create -f environment.yml
# conda activate whatif
# python -m ipykernel install --user --name whatif

name: whatif
channels:
  - conda-forge
dependencies:
- python
- pip
- pymc-base
- jupyterlab 
- ipykernel
- jupyterlab_code_formatter 
- python-graphviz
- black 
- isort
- statsmodels
- pip:
  - daft
  - causalpy==0.0.6
